### ISSUE TITLE
Tracking LWG progress through the proposed wording of P2300

### ISSUE THREAD

**Issue by ericniebler** [cplusplus/sender-receiver#203]
- [x] Exception handling **[except]**
  - [x] Special functions **[except.special]**
    - [x] General **[except.special.general]**
      - [x] The `std::terminate` function **[except.terminate]**
- [x] Library introduction **[library]**
- [x] General utilities library **[utilities]**
  - [x] Function objects **[function.objects]**
    - [x] Header `<functional>` synopsis **[functional.syn]**
    - [x] `tag_invoke` **[func.tag_invoke]**
- [x] Thread support library **[thread]**
  - [x] Stop tokens **[thread.stoptoken]**
    - [x] Header `<stop_token>` synopsis **[thread.stoptoken.syn]**
    - [x] Stop token concepts **[thread.stoptoken.concepts]**
    - [x] Class `stop_token` **[stoptoken]**
      - [x] General **[stoptoken.general]**
    - [x] Class `never_stop_token` **[stoptoken.never]**
      - [x] General **[stoptoken.never.general]**
    - [x] Class `in_place_stop_token` **[stoptoken.inplace]**
      - [x] General **[stoptoken.inplace.general]**
      - [x] Constructors, copy, and assignment **[stoptoken.inplace.cons]**
      - [x] Members **[stoptoken.inplace.mem]**
      - [x] Non-member functions **[stoptoken.inplace.nonmembers]**
    - [x] Class `in_place_stop_source` **[stopsource.inplace]**
      - [x] General **[stopsource.inplace.general]**
      - [x] Constructors, copy, and assignment **[stopsource.inplace.cons]**
      - [x] Members **[stopsource.inplace.mem]**
    - [x] Class template `in_place_stop_callback` **[stopcallback.inplace]**
      - [x] General **[stopcallback.inplace.general]**
      - [x] Constructors and destructor **[stopcallback.inplace.cons]**
  - [x] Execution control library **[exec]**
    - [x] General **[exec.general]**
    - [x] Queries and queryables **[exec.queryable]**
      - [x] General **[exec.queryable.general]**
      - [x] `queryable` concept **[exec.queryable.concept]**
    - [x] Asynchronous operations **[async.ops]**
    - [x] Header `<execution>` synopsis **[exec.syn]**
    - [x] Queries **[exec.queries]**
      - [x] `std::forwarding_query` **[exec.fwd.env]**
      - [x] `std::get_allocator` **[exec.get.allocator]**
      - [x] `std::get_stop_token` **[exec.get.stop.token]**
      - [x] `execution::get_env` **[exec.get.env]**
      - [x] `execution::get_domain` **[exec.get.domain]**
      - [x] `execution::get_scheduler` **[exec.get.scheduler]**
      - [x] `execution::get_delegatee_scheduler` **[exec.get.delegatee.scheduler]**
      - [x] `execution::get_forward_progress_guarantee` **[exec.get.forward.progress.guarantee]**
      - [x] `this_thread::execute_may_block_caller` **[exec.execute.may.block.caller]**
      - [x] `execution::get_completion_scheduler` **[exec.completion.scheduler]**
    - [x] Schedulers **[exec.sched]**
    - [x] Receivers **[exec.recv]**
      - [x] Receiver concepts **[exec.recv.concepts]**
      - [x] `execution::set_value` **[exec.set.value]**
      - [x] `execution::set_error` **[exec.set.error]**
      - [x] `execution::set_stopped` **[exec.set.stopped]**
    - [x] Operation states **[exec.opstate]**
      - [x] `execution::start` **[exec.opstate.start]**
    - [x] Senders **[exec.snd]**
      - [x] General **[exec.snd.general]**
      - [x] Sender concepts **[exec.snd.concepts]**
      - [x] Awaitable helpers **[exec.awaitables]**
      - [x] `execution::default_domain` **[exec.domain.default]**
        - [x] Static members **[exec.domain.default.statics]**
      - [x] `execution::transform_sender` **[exec.snd.transform]**
      - [x] `execution::apply_sender` **[exec.snd.apply]**
      - [x] `execution::get_completion_signatures` **[exec.getcomplsigs]**
      - [x] `execution::connect` **[exec.connect]**
      - [x] Sender factories **[exec.factories]**
        - [x] `execution::schedule` **[exec.schedule]**
        - [x] `execution::just`, `execution::just_error`, `execution::just_stopped` **[exec.just]**
        - [x] `execution::read` **[exec.read]**
      - [x] Sender adaptors **[exec.adapt]**
        - [x] General **[exec.adapt.general]**
        - [x] Sender adaptor closure objects **[exec.adapt.objects]**
        - [x] `execution::on` **[exec.on]**
        - [x] `execution::transfer` **[exec.transfer]**
        - [x] `execution::schedule_from` **[exec.schedule.from]**
        - [x] `execution::then`, `execution::upon_error`, `execution::upon_stopped` **[exec.then]**
        - [x] `execution::let_value`, `execution::let_error`, `execution::let_stopped`, **[exec.let]**
        - [x] `execution::bulk` **[exec.bulk]**
        - [x] `execution::split` and `execution::ensure_started` **[exec.split]**
        - [x] `execution::when_all` **[exec.when.all]**
        - [x] `execution::into_variant` **[exec.into.variant]**
        - [x] `execution::stopped_as_optional` **[exec.stopped.as.optional]**
        - [x] `execution::stopped_as_error` **[exec.stopped.as.error]**
      - [x] Sender consumers **[exec.consumers]**
        - [x] `execution::start_detached` **[exec.start.detached]**
        - [x] `this_thread::sync_wait` **[exec.sync.wait]**
    - [x] `execution::execute` **[exec.execute]**
    - [x] Sender/receiver utilities **[exec.utils]**
      - [x] `execution::receiver_adaptor` **[exec.utils.rcvr.adptr]**
        - [x] Non-member functions **[exec.utils.rcvr.adptr.nonmembers]**
      - [x] `execution::completion_signatures` **[exec.utils.cmplsigs]**
      - [x] `execution::transform_completion_signatures` **[exec.utils.tfxcmplsigs]**
    - [x] Execution contexts **[exec.ctx]**
      - [x] `run_loop` **[exec.run.loop]**
        - [x] Associated types **[exec.run.loop.types]**
        - [x] Constructor and destructor **[exec.run.loop.ctor]**
        - [x] Member functions **[exec.run.loop.members]**
    - [x] Coroutine utilities **[exec.coro.utils]**
      - [x] `execution::as_awaitable` **[exec.as.awaitable]**
      - [x] `execution::with_awaitable_senders` **[exec.with.awaitable.senders]**

**Comment by lewissbaker** [comment]
Closing as LWG is now done with P2300 and it passed plenary vote in St. Louis.
